version: 2.1

docker_image: &docker_image
  - image: circleci/node:latest

jobs:
  build:
    docker:
      - <<: *docker_image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn add
      - save_cache:
          key: "npm packages"
          paths:
            - /src/node_modules
      - run:
          name: Run tests
          command: yarn run lint
  test:
    docker:
      - <<: *docker_image
    steps:
      - checkout
      - restore_cache:
          key: "npm packages"
      - run:
          name: Run tests
          command: npm run test
  analyze:
    docker:
      - <<: *docker_image
    steps:
      - checkout
      - restore_cache:
          key: "npm packages"
      - run:
          name: Run tests
          command: yarn audit

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test